spring.application.name=Mahavkansha


#mysql db configuration
# data source url
spring.datasource.url=jdbc:mysql://localhost:3306/Mahavkansha
spring.datasource.username=root
spring.datasource.password=Utkarshahu@18
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa configuration
spring.jpa.show-sql=true

#creating schema and tables
spring.jpa.hibernate.ddl-auto=update

